cloud:
  aws:
    credentials:
      #aws access-key
      access-key: AKIARVCCB2KYWVSRDYGT
      #aws secret-key
      secret-key: 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
      #aws region (서울)
    region:
      static: ap-northeast-2
      #버킷 이름
    s3:
      bucket: fileuploaddearbucket
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB

