# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]

env:
  DOCKER_IMG_FULL_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMG_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Zulu OpenJDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: make application.properties
        run: |
          echo "pwd & ls -a ."
          pwd
          ls -a .
          
          echo "mkdir & touch"
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          pwd
          ls -a .

          echo "copy properties"
          echo "${{ secrets.AWS_ACCESS_KEY }}" >> ./application.properties
          echo "${{ secrets.AWS_SECRET_KEY }}" >> ./application.properties
          echo "${{ secrets.AWS_RESION }}" >> ./application.properties
          echo "${{ secrets.AWS_BUCKET }}" >> ./application.properties
          echo "${{ secrets.AWS_STACK_AUTO }}" >> ./application.properties
          
          echo "${{ secrets.MANAGEMENT_BASE_PATH }}" >> ./application.properties
          echo "${{ secrets.MANAGEMENT_INCLUDE }}" >> ./application.properties
          echo "${{ secrets.MANAGEMENT_APPLICATION }}" >> ./application.properties
          echo "${{ secrets.MANAGEMENT_ENDPOINT_METRICS_ENABLE }}" >> ./application.properties
          echo "${{ secrets.MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLE }}" >> ./application.properties
          
          echo "${{ secrets.JWT_HEADER }}" >> ./application.properties
          echo "${{ secrets.JWT_REFRESH_TIME_SEC }}" >> ./application.properties
          echo "${{ secrets.JWT_ACCESS_TIME_SEC }}" >> ./application.properties
          echo "${{ secrets.JWT_SECRET }}" >> ./application.properties
          echo "${{ secrets.KAKAO_CLIENT_SECRET }}" >> ./application.properties
          
          echo "${{ secrets.KAKAO_CLIENT_REDIRECT_URI }}" >> ./application.properties
          echo "${{ secrets.KAKAO_CLIENT_ID }}" >> ./application.properties
          echo "${{ secrets.OPENVIDU_SECRET }}" >> ./application.properties
          echo "${{ secrets.OPENVIDU_URL }}" >> ./application.properties
          echo "${{ secrets.SPRING_DB_USERNAME }}" >> ./application.properties
          
          echo "${{ secrets.SPRING_DB_URL }}" >> ./application.properties
          echo "${{ secrets.SPRING_DB_PW }}" >> ./application.properties
          echo "${{ secrets.SPRING_HIDDEN_METHOD_FILTER_ENABLE }}" >> ./application.properties
          echo "${{ secrets.SPRING_MVC_PATHMATCH_MATCHING_STRATEGY }}" >> ./application.properties
          echo "${{ secrets.SPRING_SERVLET_MAX_FILE_SIZE }}" >> ./application.properties
          
          echo "${{ secrets.SPRING_SERVLET_MAX_REQUEST_SIZE }}" >> ./application.properties

        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker img build & Dockerhub push
        run: |
          docker build -t $DOCKER_IMG_FULL_NAME:${GITHUB_SHA::7} .
          docker push $DOCKER_IMG_FULL_NAME:${GITHUB_SHA::7}

      - name: Docker Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: GITHUB_SHA,DOCKER_IMG_FULL_NAME
          script: |
            yes | docker image prune -a
            docker pull $DOCKER_IMG_FULL_NAME:${GITHUB_SHA::7}
            docker stop spring
            docker run -d --rm --name spring -p 8443:8443 $DOCKER_IMG_FULL_NAME:${GITHUB_SHA::7}



